# Generated by Django 4.2.16 on 2025-10-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='author',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
