# Generated by Django 4.2.16 on 2025-10-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contender',
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
    ]
