# Generated by Django 4.2.16 on 2025-10-06 11:04

from django.conf import settings
from django.db import migrations
from django.db.models import Count


def _clean_duplicate_feed_reactions(apps, schema_editor):
    FeedReaction = apps.get_model('feeds', 'FeedReaction')
    # Find duplicate (feed_id, user_id) pairs
    duplicates = (
        FeedReaction.objects.values('feed_id', 'user_id')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )

    for dup in duplicates:
        feed_id = dup['feed_id']
        user_id = dup['user_id']
        qs = FeedReaction.objects.filter(feed_id=feed_id, user_id=user_id).order_by('created_at', 'id')
        # Keep the earliest reaction (by created_at, then id) and delete the rest
        ids = list(qs.values_list('id', flat=True))
        if len(ids) <= 1:
            continue
        keep_id = ids[0]
        FeedReaction.objects.filter(feed_id=feed_id, user_id=user_id).exclude(id=keep_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0002_alter_feed_options_rename_content_feed_description_and_more'),
    ]

    operations = [
        migrations.RunPython(_clean_duplicate_feed_reactions, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='feedreaction',
            unique_together={( 'feed', 'user')},
        ),
    ]
