# Generated by Django 4.2.16 on 2025-10-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_feedreaction_unique_together'),
    ]

    operations = [
    ]
