# Generated by Django 4.2.16 on 2025-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
        migrations.AddField(
            model_name='reply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reply_files/'),
        ),
    ]
