# Generated by Django 4.2.16 on 2025-10-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_alter_department_options_alter_institution_options_and_more'),
        ('user_messages', '0002_message_file_reply_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionFilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_file', models.BooleanField(default=False)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
    ]
