# Generated by Django 4.2.16 on 2025-09-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('crime', 'Crime'), ('environment', 'Environment'), ('accident', 'Accident')], default='crime', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.institution'),
        ),
    ]
