# Generated by Django 4.2.16 on 2025-10-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_alter_department_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'institution')},
        ),
        migrations.CreateModel(
            name='InstitutionFilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_file', models.BooleanField(default=False)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_permission', to='institutions.institution')),
            ],
        ),
    ]
