# Generated by Django 4.2.16 on 2025-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_types', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemtype',
            name='created_at',
        ),
        migrations.AddField(
            model_name='problemtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
