# Generated by Django 4.2.16 on 2025-10-09 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problem_types', '0002_remove_problemtype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
